### ISSUE TITLE
Contrato De desarrollo de Sofware

### ISSUE THREAD

**Issue by kirus21** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-dream-team1#1]
[Reporte Contrato-para-el-desarrollo-de-Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-dream-team1/files/10189292/Reporte.Contrato-para-el-desarrollo-de-Software.pdf)

**Comment by IMA-G** [comment]
48% de 50%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
